/**
* @File Name : SharePointAuth.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : April 13, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | April 13, 2025 |   | Initial Version
**/

public class SharePointAuth {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}